
language: php

matrix:
  include:
  - php: 7.1
    env: PHPUNIT_VERSION="^7"
    env: WP_TRAVISCI=travis:js
  - php: 7.3
    env: PHPUNIT_VERSION="^7"
  - php: 7.2
    env: PHPUNIT_VERSION="^7"
  - php: 7.1
    env: PHPUNIT_VERSION="^7"
  - php: 7.0
  - php: 5.6
  - php: 5.6
    env: WP_TRAVIS_OBJECT_CACHE=true
    services: memcached
  - php: 5.5
  - php: 5.3
    dist: precise
  - php: 5.2
    dist: precise
  - php: nightly

  allow_failures:
  - php: nightly

  fast_finish: true

env:
  global:
    - WP_VERSION=master # Git equivalent of SVN /trunk
    - PHPUNIT_VERSION="travis"

# Before install, failures in this section will result in build status 'errored'
before_install:
  # clone the WordPress develop repo
  - WP_DEVELOP_DIR=/tmp/wordpress
  - git clone --depth=1 --branch="master" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
  - if [[ $PHPUNIT_VERSION != "travis" ]]; then composer require phpunit/phpunit:${PHPUNIT_VERSION}; fi

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost master
